version: "3"

services:
  redis-master:    
    container_name: "redis"
    image: "redis:alpine"
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes
  notifier:
    build: .
    network_mode: "host"
    
