[ConnectorApi]
    # The port on which the Hub listens for subscriptions
    Port = "5000"

    # Username is the username needed to authorize an observer to push data
    Username = ""

    # Password is the password needed to authorize an observer to push event data
    Password = ""

    # CheckDuplicates signals if the events received from observers have been already pushed to clients
    # Requires a redis instance/cluster and should be used when multiple observers push from the same shard
    CheckDuplicates = true

[Azure]
    KeyVault = "trustmarketdevnetvault"
    Topic = 'mvx_events_raw_devnet'

[Redis]
    # The url used to connect to a pubsub server
    # Note: not required for running in the notifier mode
    Url = "redis://localhost:6379/0"

    # The pubsub channel used for publishing/subscribing
    # Note: not required for running in the notifier mode
    Channel = "pub-sub"

    # The master name for failover client
    MasterName = "mymaster"

    # The sentinel url for failover client
    SentinelUrl = "localhost:26379"

    # The redis connection type. Options: | instance | sentinel |
    # instance - it will try to connect to a single redis instance
    # sentinel - it will try to connect to redis setup with master, slave and sentinel instances
    ConnectionType = "instance"

    # Time to live (in minutes) for redis lock entry
    TTL = 30

[RabbitMQ]
    # The url used to connect to a rabbitMQ server
    # Note: not required for running in the notifier mode
    Url = "amqp://guest:guest@localhost:5672"

    # The exchange which holds all logs and events
    [RabbitMQ.EventsExchange]
        Name = "all_events_dev"
        Type = "fanout"

    # The exchange which holds revert events
    [RabbitMQ.RevertEventsExchange]
        Name = "revert_events_dev"
        Type = "fanout"

    # The exchange which holds finalized block events
    [RabbitMQ.FinalizedEventsExchange]
        Name = "finalized_events_dev"
        Type = "fanout"

    # The exchange which holds block txs events
    [RabbitMQ.BlockTxsExchange]
        Name = "block_txs_dev"
        Type = "fanout"

    # The exchange which holds block scrs events
    [RabbitMQ.BlockScrsExchange]
        Name = "block_scrs_dev"
        Type = "fanout"
